services:
  - type: web
    name: whatsapp-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: frankfurt
    disk:
      name: whatsapp-sessions
      mountPath: /app/sessions
      sizeGB: 1
    envVars:
      - key: SESSIONS_PATH
        value: /app/sessions